"""Add currency column to menu_item

Revision ID: 0e04ea6f3aad
Revises: 20afd62bbbc1
Create Date: 2025-03-30 01:00:42.800118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e04ea6f3aad'
down_revision = '20afd62bbbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
