"""Add country, currency and tax_rate fields to User model

Revision ID: bbc280b7c60a
Revises: 8e85d2fe4183
Create Date: 2025-03-31 23:51:21.303965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc280b7c60a'
down_revision = '8e85d2fe4183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('country')
    # ### end Alembic commands ###
